# Args: <cam_file> <obj_file> <output_dir>
{
  "version": 2,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py",
      "python-dateutil==2.1",
      "numpy",
      "Pillow",
      "opencv-contrib-python",
      "scipy"
    ]
  },
  "global": {
    "all": {
      "output_dir": "<args:2>",
      "resolution_x": 1280,
      "resolution_y": 720
    }
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config": {}
    },
    {
      "module": "loader.SuncgLoader",
      "config": {
        "path": "<args:1>"
      }
    },
    {
      "module": "camera.CameraLoader",
      "config": {
        "path": "<args:0>",
        "file_format": "location rotation/value _ _ _ fov _ _",
        "source_frame": ["X", "-Z", "Y"],
        "default_cam_param": {
          "rotation": {
            "format": "forward_vec"
          },
          "fov_is_half": true,
          "interocular_distance": 0.05,
          "stereo_convergence_mode": "PARALLEL",
          "convergence_distance": 0.00001,
          "cam_K": [650.018, 0, 637.962, 0, 650.018, 355.984, 0, 0 ,1],
          "resolution_x": 1280,
          "resolution_y": 720
        },
      }
    },
    {
      "module": "lighting.SuncgLighting",
      "config": {}
    },
    {
      "module": "renderer.NormalRenderer",
      "config": {}
    },
    {
      "module": "renderer.SegMapRenderer",
      "config": {}
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "render_depth": true,
        "stereo": true,
      }
    },
    {
      "module": "writer.StereoGlobalMatchingWriter",
      "config": {
        "focal_length": 650.018,
        "enable_disparity_filter": false
      }
    },
    {
      "module": "writer.Hdf5Writer",
    }
  ]
}