from blenderproc.python.lighting.SuncgLighting import light_suncg_scene
from blenderproc.python.lighting.SurfaceLighting import light_surface
from blenderproc.python.lighting.IntersectingSpotLight import add_intersecting_spot_lights_to_camera_poses
